[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
# ... rest of lint config ...
exclude_lints = ["unwrapped-modifier-logic", "mixed-case-function"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
